POST http://localhost:8080/events/process
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="file"; filename="input.txt"
Content-Type: text/plain

< ./src/main/resources/input.txt
--BOUNDARY--
